version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: artigos-grao-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: article_db        
      MYSQL_USER: mysql                
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
